# Generated by Django 3.2.25 on 2025-11-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20241220_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='cfactor',
            new_name='amt',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='aunit',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='brand',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='punit',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='taxtype',
        ),
    ]
