# Generated by Django 3.2.25 on 2025-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20251114_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rate',
            field=models.CharField(max_length=255),
        ),
    ]
