# Generated by Django 3.2.25 on 2025-11-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0002_auto_20241230_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewarsPoints',
        ),
    ]
